<!DOCTYPE html>
<html>
    <head>
        <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
        <title>Jeroboam</title>
        <meta name="author" content="Jeroboam" />
        <link href='http://fonts.googleapis.com/css?family=Lato:300|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
        <style type="text/css">
            body { background:#222; color:#DDD; margin:0; padding:0; border:0; width:100%; font-family: 'Lato', sans-serif; }
            #container { clear:both; margin:0px; padding:0px; }
            #container:before, #container:after { content:""; display:table; }
            #container:after { clear:both; }
            .column { display: block; float:left; margin: 0 1%; }
            #left { width: 20%; padding:1em 0; background-color:#444; }
            #left ul { list-style:none; margin:2em 1em; padding:0; }
            #left ul li { margin-bottom:1em; list-style-position:inside; white-space: nowrap;
                          overflow: hidden; text-overflow: ellipsis; }
            #left ul li a { color:#DDD; text-decoration:none; }
            header { text-align:center; font-size:30px;
                     font-family: 'Open Sans Condensed', sans-serif; }
            footer { text-align:center; font-size:12px; }
            header a, footer a { color:#DDD; text-decoration:none; }
            #right { width: 76%; }
            @media only screen and (max-width: 480px) {
	            .col { margin: 1% 0; }
	            #left, #right { width: 100%; }
            }
        </style>
    </head>
    <body>

    <div id="container">
	    <div id="left" class="column">
            <header><a href="/">JEROBOAM</a></header>
            <ul>
                % for folder in tree:
                    % if folder:
                        % space = '&nbsp;' * 3 * len([slash for slash in folder if slash == '/'])
                        % folder_text = folder.split('/')[-1]
                        <li><a href="/{{folder}}">{{!space}}{{folder_text}}</a></li>
                    % end
                % end
            </ul>
            % from time import strftime
            % date = strftime("%Y-%m-%d %H:%M:%S")
            <footer><a href="http://github.com">Generated by Jeroboam on {{date}}.</a></footer>
	    </div>
	    <div id="right" class="column">
            <h2>Albums</h2>
            % for picture in pictures:
            <p>{{picture}}</p>
            % end
	    </div>
    </div>

    </body>
</html>
