<!DOCTYPE html>
<html>
    <head>
        <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
        <title>Jeroboam</title>
        <meta name="author" content="Jeroboam" />
        <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Lato:300|Open+Sans+Condensed:300'>
        <link rel='stylesheet' type='text/css' href='//cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css'>
        <style type="text/css">
            html { -ms-touch-action:manipulation; touch-action:manipulation; }
            body { background:#222; color:#DDD; margin:0; padding:0; border:0; width:100%; font-family:'Lato', sans-serif; }
            #main { clear:both; margin:0px; padding:0px; }
            #main:before, #main:after { content:""; display:table; }
            #main:after { clear:both; }
            .column { display:block; float:left; margin:0 1em; }
            #left { width: 20%; padding:1em 0; background-color:#444; }
            #left ul { list-style:none; margin:2em 1em; padding:0; }
            #left ul li { margin-bottom:1em; list-style-position:inside; white-space:nowrap;
                          overflow:hidden; text-overflow:ellipsis; }
            #left ul li a { color:#DDD; text-decoration:none; }
            header { text-align:center; font-size:30px; font-family:'Open Sans Condensed', sans-serif; }
            footer { text-align:center; font-size:12px; padding:1em; }
            header a, footer a { color:#DDD; text-align:center; text-decoration:none; }
            #right { width:76%; margin:1em 0; text-align:center; }
            .picture { float:left; margin:1em; padding:0; }
            .picture img { -moz-border-radius:15px; border-radius:15px; }
            #message { background-color:#444; -moz-border-radius:15px; border-radius:15px;
                       font-size:2em; margin:3em; padding:5% 0; text-align:center; }
            @media only screen and (max-width: 480px) {
                .col { margin:1% 0; }
                #main, #left, #right { width:100%; }
            }
        </style>
    </head>
    <body>

    <div id="main">
        <div id="left" class="column">
            <header><a href="/">JEROBOAM</a></header>
            <ul>
                % for dico in tree:
                    % space = '&nbsp;' * 3 * len([slash for slash in dico['path'] if slash == '/'])
                    % folder_text = dico['path'].split('/')[-1]
                    % if dico['nbfiles'] or dico['nbdirs']:
                        % if dico['nbfiles']:
                            <li><a href="/{{dico['path']}}">
                        % else:
                            <li title="Empty directory">
                        % end
                        % if folder_text:
                            {{!space}}{{folder_text}}
                        % else:
                            ~
                        % end
                        % if dico['nbfiles']:
                            </a>
                        % end
                        </li>
                    % end
                % end
            </ul>
            <footer><a href="https://github.com/stephanepechard/jeroboam">Generated by Jeroboam on {{date}}</a></footer>
        </div>
        <div id="right" class="column">
            % if pictures:
                % for pic in pictures:
                    % pic_text = pic.split('/')[-1]
                    <div class="picture appbox">
                        <a href="/{{pic}}" data-lightbox="lb" data-title="{{pic_text}}"><img src="/cache/{{pic}}" /></a>
                    </div>
                % end
            % else:
                <div id="message"><div style="padding:10% 0;">{{message}}</div></div>
            % end
        </div>
    </div>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js"></script>
    </body>
</html>
